### ISSUE TITLE
Doesn't seem to work...

### ISSUE THREAD

**Issue by aguaman15** [bendodson/homebridge-applescript#1]
If you've installed this Homebridge plugin and it doesn't seem to work, the problem may simply be that Terminal is not open and running. According to kind and patient developer, when you run Homebridge as a launchctl daemon service it doesn’t have access to any form of GUI which means AppleScript doesn’t work. There is no way around that unfortunately so the plugin will never work if you are using Homebridge as a daemon service. 

I figure this might help someone else, and GitHub is as good a place as any to post this. Thank you, Ben.

**Comment by abort-retry-ignore** [comment]
Thank you!  I was wondering why this plugin just won't work if starting homebridge on boot!
